### ISSUE TITLE
Erro ao autorizar NFe emitida por MEI (CRT = 4)

### ISSUE THREAD

**Issue by VanguardaSistemas** [nfewizard-org/nfewizard-io#29]
Bom dia!

Tenho alguns clientes que são MEI. Quando fui autorizar deu erro com a validação do campo "CRT", que agora passa a aceitar o valor 4 também, para identificar o MEI.

Pra corrigir temporariamente, eu copiei os schemas atualizados para a pasta node_modules/nfewizard-io/dist/cjs/schemas

Vlww

**Comment by Maurelima** [comment]
@VanguardaSistemas, correção liberada em [74e67e4](https://github.com/nfewizard-org/nfewizard-io/commit/74e67e49bf8cdc2f828a4ff4f50dd0721ee90d44).

Atualizar lib para versão: [0.2.2](https://www.npmjs.com/package/nfewizard-io/v/0.2.2)

Não possuo um MEI no momento para teste, caso possa testar e me retornar ficarei grato!

**Comment by VanguardaSistemas** [comment]
Beleza. Vou atualizar e testar, já posto aqui se deu certo

**Comment by VanguardaSistemas** [comment]
Deu certo! Autorizou.
