### ISSUE TITLE
Erro ao instalar a biblioteca

### ISSUE THREAD

**Issue by ThalesAugusto0** [nfewizard-org/nfewizard-io#4]
### Ambiente de Desenvolvimento

- **Node.js versão**: v20.12.2
- **Sistema operacional**: Windows 11
- **Versão da biblioteca `nfewizard-io`**: ^0.0.4
- **Gerenciador de pacotes**: yarn

### Passos para Reproduzir

1. Instalei a biblioteca `nfewizard-io` usando `yarn add nfewizard-io` ou `npm install nfewizard-io`.
2. Configurei o projeto para usar módulos ES6 com `"type": "module"` no `package.json`.
3. Tentei importar o módulo com a linha: `import NFeWizard from 'nfewizard-io';`
4. Recebi o erro `ERR_MODULE_NOT_FOUND`.

### Tentativas de Resolução

- Verifiquei se o arquivo existe no caminho especificado.
- Limpei o cache do `yarn` e do `npm` e reinstalei as dependências.

**Comment by Maurelima** [comment]
Obrigado por reportar, Thales!

Efetuei o teste conforme você descreveu e realmente está ocorrendo esse problema com javascript.

Provisoriamente, se possível, recomendo utilizar typescript.

Já estou trabalhando para a resolução do problema.

**Comment by Maurelima** [comment]
### Problema:
1. Ao tentar utilizar a biblioteca no JavaScript, ocorreu o erro "ERR_MODULE_NOT_FOUND". Este problema foi causado porque, após a compilação do TypeScript, os arquivos JavaScript gerados não incluíam as extensões de arquivo (.js) nos imports. Enquanto o TypeScript consegue resolver os caminhos dos módulos sem a extensão, o Node.js exige a presença das extensões para resolver corretamente os módulos ES.

2. Durante a assinatura de XML, o método `assinarXML` estava falhando devido à ausência das propriedades `digestAlgorithm` e `signatureAlgorithm`.

### Solução:
1. Foi adicionado um passo adicional no script de build para garantir que todos os imports nos arquivos gerados incluam a extensão .js. Além disso, foram ajustados os imports de arquivos JSON para incluir a asserção de tipo necessária (`assert { type: "json" }`). Isso garante que o Node.js possa resolver todos os módulos corretamente, evitando os erros de importação.

2. Ao assinar o XML, foram incluídos os parâmetros `digestAlgorithm` e `signatureAlgorithm` na configuração do objeto `SignedXml`. Estes parâmetros são essenciais para especificar os algoritmos utilizados na digestão e na assinatura, garantindo que o processo de assinatura ocorra sem erros.

### Mudanças:
- Adicionado script para adicionar automaticamente a extensão .js aos imports após a compilação do TypeScript.
- Ajustados os imports de arquivos JSON para incluir a asserção de tipo.
- Adicionadas as propriedades `digestAlgorithm` e `signatureAlgorithm` ao método de assinatura de XML para garantir a conformidade com os requisitos de assinatura.

### Resumo:
Essas mudanças asseguram que os arquivos gerados pela compilação TypeScript sejam compatíveis com os requisitos de resolução de módulos do Node.js, eliminando o erro "ERR_MODULE_NOT_FOUND" ao utilizar a biblioteca no JavaScript. Além disso, garantem que o processo de assinatura de XML ocorra corretamente, resolvendo os problemas relacionados à ausência de algoritmos de digestão e assinatura.

### Commit e Versão:
A correção foi implementada no commit [5c43ee7](https://github.com/nfewizard-org/nfewizard-io/commit/5c43ee7c704a6c70999f805a67283b59a2742b4e) e está incluída na versão 0.0.5.
